name: Deploy to DigitalOcean Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/shop-backend:latest
            docker stop shop-backend || true
            docker rm shop-backend || true
            docker run -d --name shop-backend -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/shop-backend:latest
